services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: payflow
      DB_USERNAME: payflow
      DB_PASSWORD: secret
      REDIS_HOST: redis
      QUEUE_CONNECTION: redis

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: payflow
      MYSQL_USER: payflow
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    depends_on:
      - nginx

volumes:
  mysql_data:
